### ISSUE TITLE
During `make test` TestUpdateRepoPost fails

### ISSUE THREAD

**Issue by DmitryFrolovTri** [DmitryFrolovTri/gitea-limit-repo-size#10]
```
--- FAIL: TestUpdateRepoPost (24.55s)
panic: interface conversion: interface {} is nil, not *forms.UpdateGlobalRepoFrom [recovered]
	panic: interface conversion: interface {} is nil, not *forms.UpdateGlobalRepoFrom

goroutine 132 [running]:
testing.tRunner.func1.2({0x1ed6100, 0xc001c15a40})
	/home/puni/.gvm/gos/go1.19/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/home/puni/.gvm/gos/go1.19/src/testing/testing.go:1399 +0x39f
panic({0x1ed6100, 0xc001c15a40})
	/home/puni/.gvm/gos/go1.19/src/runtime/panic.go:884 +0x212
code.gitea.io/gitea/routers/web/admin.UpdateRepoPost(0xc00291c600)
	/home/puni/sources/mine/gitea-sapk-test1/routers/web/admin/repos.go:48 +0x4e6
code.gitea.io/gitea/routers/web/admin.TestUpdateRepoPost(0x0?)
	/home/puni/sources/mine/gitea-sapk-test1/routers/web/admin/repos_test.go:23 +0x1c5
testing.tRunner(0xc0001829c0, 0x25fa518)
	/home/puni/.gvm/gos/go1.19/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/home/puni/.gvm/gos/go1.19/src/testing/testing.go:1493 +0x35f
FAIL	code.gitea.io/gitea/routers/web/admin	26.261s

```

**Comment by DmitryFrolovTri** [comment]
Fixed with https://github.com/DmitryFrolovTri/gitea/commit/80f8977e596db4fbeac43c37af3c123c4c4b95f6 commit. Test ran fine
